# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-22 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=75, null=True)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'contacts',
                'verbose_name': 'contact',
                'ordering': ('created',),
            },
        ),
    ]
